


"use strict";const gCc=Components.classes;const gCi=Components.interfaces;const CLASS_NAME="AVIM JavaScript XPCOM component";const CLASS_ID=Components.ID("{ee7dd176-a684-4dc0-8613-62ddaef5378f}");const CONTRACT_ID="@1ec5.org/avim;1";function AVIMOverlayObserver(aWindow){this.window=aWindow;}
AVIMOverlayObserver.prototype.observe=function(subject,topic,data){if(topic!=="xul-overlay-merged"&&topic!=="sb-overlay-load")return;if(!this.window)return;if(!this.window.avim)return;this.window.avim.registerPrefs();this.window.avim.updateUI();};function AVIM(){this.wrappedJSObject=this;this.didObserveStartup=false;}
AVIM.prototype.QueryInterface=function(iid){if(iid.equals(gCi.nsIObserver)||iid.equals(gCi.nsISupports))return this;throw Components.results.NS_ERROR_NO_INTERFACE;};AVIM.getOverlayUrl=function(windowUrl){switch(windowUrl){ case"chrome://sunbird/content/calendar.xul":return"chrome://avim/content/calendarOverlay.xul"; case"chrome://editor/content/editor.xul":return"chrome://avim/content/composerOverlay.xul"; case"chrome://webrunner/content/webrunner.xul":return"chrome://avim/content/prismOverlay.xul"; case"chrome://komodo/content/komodo.xul":return"chrome://avim/content/komodoOverlay.xul"; case"chrome://bluegriffon/content/xul/bluegriffon.xul":return"chrome://avim/content/blueGriffonOverlay.xul"; case"chrome://collab/content/collab.xul":return"chrome://avim/content/collabOverlay.xul";default:return"chrome://avim/content/generalOverlay.xul";}};AVIM.prototype.onWindowOpen=function(window){let xulTypes=["text/xul","application/vnd.mozilla.xul+xml"];let manifestUrls=["chrome://browser/content/browser.xul","chrome://browser/content/preferences/preferences.xul","chrome://messenger/content/preferences/preferences.xul","chrome://dta/content/preferences/prefs.xul","chrome://tabmixplus/content/preferences/preferences.xul",];let handleEvent=function(event){let doc=event.originalTarget; if(doc.location&&doc.location.protocol==="chrome:"&&doc.contentType&&xulTypes.indexOf(doc.contentType)>=0&&manifestUrls.indexOf(doc.location.href)<0){let xulVersion=gCc["@mozilla.org/xre/app-info;1"].getService(gCi.nsIXULAppInfo).platformVersion;let overlayObserver=null;if(parseFloat(xulVersion)>=1.9){overlayObserver=new AVIMOverlayObserver(window);}
doc.loadOverlay(AVIM.getOverlayUrl(doc.location.href),overlayObserver);}
window.removeEventListener("DOMContentLoaded",handleEvent,true);};if(!window.frameElement){window.addEventListener("DOMContentLoaded",handleEvent,true);}};AVIM.prototype.observe=function(subject,topic,data){const xreSvc=gCc["@mozilla.org/xre/app-info;1"].getService(gCi.nsIXULRuntime);if(xreSvc.inSafeMode)return;const observerSvc=gCc["@mozilla.org/observer-service;1"].getService(gCi.nsIObserverService);switch(topic){case"profile-after-change":if(this.didObserveStartup)break;case"app-startup":observerSvc.addObserver(this,"domwindowopened",false);observerSvc.addObserver(this,"quit-application",false);this.didObserveStartup=true;break;case"quit-application":observerSvc.removeObserver(this,"domwindowopened",false);observerSvc.addObserver(this,"quit-application",false);break;case"domwindowopened":this.onWindowOpen(subject);}
};let AVIMFactory={createInstance:function(outer,iid){if(outer)throw Components.results.NS_ERROR_NO_AGGREGATION;return new AVIM().QueryInterface(iid);}};let AVIMModule={registerSelf:function(compMgr,fileSpec,loc,type){compMgr=compMgr.QueryInterface(gCi.nsIComponentRegistrar);compMgr.registerFactoryLocation(CLASS_ID,CLASS_NAME,CONTRACT_ID,fileSpec,loc,type);let catMgr=gCc["@mozilla.org/categorymanager;1"].getService(gCi.nsICategoryManager);try{catMgr.addCategoryEntry("app-startup",CLASS_NAME,"service,"+CONTRACT_ID,true,true);}
catch(exc){catMgr.addCategoryEntry("profile-after-change",CLASS_NAME,"service,"+CONTRACT_ID,true,true);}},unregisterSelf:function(compMgr,loc,type){compMgr=compMgr.QueryInterface(gCi.nsIComponentRegistrar);compMgr.unregisterFactoryLocation(CLASS_ID,loc);let catMgr=gCc["@mozilla.org/categorymanager;1"].getService(gCi.nsICategoryManager);try{catMgr.addCategoryEntry("app-startup",CLASS_NAME,true);}
catch(exc){catMgr.addCategoryEntry("profile-after-change",CLASS_NAME,true);}},getClassObject:function(compMgr,cid,iid){if(!iid.equals(gCi.nsIFactory)){throw Components.results.NS_ERROR_NOT_IMPLEMENTED;}
if(cid.equals(CLASS_ID))return AVIMFactory;throw Components.results.NS_ERROR_NO_INTERFACE;},canUnload:function(compMgr){return true;}};function NSGetModule(compMgr,fileSpec){return AVIMModule;}
function NSGetFactory(cid){let cidStr=cid.toString();if(cidStr==CLASS_ID)return AVIMFactory;throw Components.results.NS_ERROR_FACTORY_NOT_REGISTERED;}